# Generated by Django 3.2.9 on 2022-07-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_url_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='http_status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
